# generated by the pymodd_library_validator


@action
def send_coins_to_player(coins, player, comment=None, disabled=False, run_on_client=False):
	return {
		'type': 'sendCoinsToPlayer',
		'coins': to_dict(coins),
		'player': to_dict(player),
	}


@action
def add_chat_filter(words, comment=None, disabled=False, run_on_client=False):
	return {
		'type': 'addChatFilter',
		'words': to_dict(words),
	}