[package]
name = "pymodd"
version = "0.1.0"
edition = "2021"

[lib]
name = "pymodd_generator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
serde_json = "1.0"
