static TRIGGERS: phf::OrderedMap<&'static str, &'static str> = ::phf::OrderedMap {
    key: 10121458955350035957,
    disps: &[
        (0, 10),
        (0, 26),
        (7, 43),
        (1, 9),
        (1, 10),
        (1, 15),
        (4, 7),
        (1, 0),
        (20, 7),
        (1, 1),
    ],
    idxs: &[
        23,
        32,
        26,
        24,
        43,
        28,
        13,
        16,
        4,
        0,
        15,
        41,
        45,
        2,
        21,
        7,
        46,
        22,
        39,
        44,
        35,
        38,
        48,
        19,
        11,
        9,
        31,
        25,
        10,
        33,
        27,
        36,
        1,
        17,
        34,
        29,
        5,
        6,
        14,
        30,
        12,
        3,
        8,
        20,
        37,
        18,
        47,
        40,
        42,
    ],
    entries: &[
        ("gameStart", GAME_START),
        ("frameTick", EVERY_FRAME),
        ("secondTick", EVERY_SECOND),
        ("serverShuttingDown", SERVER_SHUTTING_DOWN),
        ("unitTouchesWall", UNIT_TOUCHES_WALL),
        ("unitUsesItem", UNIT_USES_ITEM),
        ("unitAttributeBecomesZero", UNIT_ATTRIBUTE_BECOMES_ZERO),
        ("unitStartsUsingAnItem", UNIT_STARTS_USING_AN_ITEM),
        ("unitAttributeBecomesFull", UNIT_ATTRIBUTE_BECOMES_FULL),
        ("unitDroppedAnItem", UNIT_DROPPED_AN_ITEM),
        ("unitEntersRegion", UNIT_ENTERS_REGION),
        ("unitTouchesItem", UNIT_TOUCHES_ITEM),
        ("unitPickedAnItem", UNIT_PICKED_AN_ITEM),
        ("unitTouchesUnit", UNIT_TOUCHES_UNIT),
        ("unitTouchesDebris", UNIT_TOUCHES_DEBRIS),
        ("unitTouchesProjectile", UNIT_TOUCHES_PROJECTILE),
        ("unitStopsUsingAnItem", UNIT_STOPS_USING_AN_ITEM),
        ("unitAttacksUnit", UNIT_ATTACKS_UNIT),
        ("unitSelectsItem", UNIT_SELECTS_ITEM),
        ("unitSelectsInventorySlot", UNIT_SELECTS_INVENTORY_SLOT),
        ("unitEntersSensor", UNIT_ENTERS_SENSOR),
        ("projectileTouchesItem", PROJECTILE_TOUCHES_ITEM),
        ("projectileTouchesDebris", PROJECTILE_TOUCHES_DEBRIS),
        ("projectileAttributeBecomesZero", PROJECTILE_ATTRIBUTE_BECOMES_ZERO),
        ("projectileTouchesWall", PROJECTILE_TOUCHES_WALL),
        ("projectileEntersSensor", PROJECTILE_ENTERS_SENSOR),
        ("playerCustomInput", PLAYER_CUSTOM_INPUT),
        ("playerAttributeBecomesFull", PLAYER_ATTRIBUTE_BECOMES_FULL),
        ("playerJoinsGame", PLAYER_JOINS_GAME),
        ("playerPurchasesUnit", PLAYER_PURCHASES_UNIT),
        ("playerLeavesGame", PLAYER_LEAVES_GAME),
        ("playerAttributeBecomesZero", PLAYER_ATTRIBUTE_BECOMES_ZERO),
        ("playerSendsChatMessage", PLAYER_SENDS_CHAT_MESSAGE),
        ("itemAttributeBecomesFull", ITEM_ATTRIBUTE_BECOMES_FULL),
        ("itemEntersRegion", ITEM_ENTERS_REGION),
        ("itemTouchesWall", ITEM_TOUCHES_WALL),
        ("itemAttributeBecomesZero", ITEM_ATTRIBUTE_BECOMES_ZERO),
        ("itemIsUsed", ITEM_IS_USED),
        ("itemEntersSensor", ITEM_ENTERS_SENSOR),
        ("raycastItemFired", RAYCAST_ITEM_FIRED),
        ("entityCreated", ENTITY_CREATED),
        ("entityTouchesWall", ENTITY_TOUCHES_WALL),
        ("entityTouchesItem", ENTITY_TOUCHES_ITEM),
        ("entityTouchesUnit", ENTITY_TOUCHES_UNIT),
        ("entityTouchesProjectile", ENTITY_TOUCHES_PROJECTILE),
        ("entityAttributeBecomesZero", ENTITY_ATTRIBUTE_BECOMES_ZERO),
        ("entityAttributeBecomesFull", ENTITY_ATTRIBUTE_BECOMES_FULL),
        ("entityEntersRegion", ENTITY_ENTERS_REGION),
        ("debrisEntersRegion", DEBRIS_ENTERS_REGION),
    ],
};
