name: Test pymodd_generator

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update local toolchain
        run: |
          rustup update

      - name: test
        run: |
          cd src
          cargo check
          cargo test --all
